<?php
/**
 * @file
 * Module file for ldap_profile_displayname.
 */

/* 
 * Implements hook_user_presave 
 */
function ldap_profile_displayname_user_presave(&$edit, $account, $category) {
  if ($category == 'account' && _mapped_fields_exist($edit)) {
    dpm($edit);
    dpm($account);
    dpm($category);
    // $category = 'account';
    $name = explode(',', $edit['field_ldap_displayname']['und'][0]['value']);
    if (isset($name[0]) && isset($name[1])) {
      $edit['field_title_name']['und'][0]['given'] = $name[1];
      $edit['field_title_name']['und'][0]['family'] = $name[0];
    }
  }
}

function ldap_profile_displayname_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    dpm($form);
    if (_mapped_fields_exist($form)) {
      $form['field_title_name']['#disabled'] = TRUE;
    }
  }
}

function _mapped_fields_exist($form) {
  return isset($form['field_ldap_displayname']) && isset($form['field_title_name']);
}